### ISSUE TITLE
Rename from mdast to remark

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-defsplit#1]
Hey! Just wanted ping and request a name change from mdast to remark!

You’ve probably already seen it but [here](https://github.com/wooorm/remark/blob/master/doc/plugins.md#renaming-from-mdast-to-remark)’s a list of tips for updating.

Let me know if I can help! :smile:

**Comment by wooorm** [comment]
P.S. as a side note, I suggest using `toUpperCase()` [here](https://github.com/eush77/mdast-defsplit/blob/9f348cbbc2b009486ffd2206b99d1cda116e17ec/index.js#L107). Currently, I think this plug-in would fail if someone specifies a definition identifier of `__proto__`. I haven’t tested it but something similar caused issues in remark.

**Comment by eush77** [comment]
Thanks!

> I suggest using toUpperCase() here. Currently, I think this plug-in would fail if someone specifies a definition identifier of `__proto__`.

I have spotted no issues with such identifiers so far, perhaps because I use `Object.create(null)` both for identifiers and links while visiting them. Is there any other reason for `toUpperCase` here, based on your experience?

**Comment by wooorm** [comment]
Oh, that’s probably fine too, the only reason was for prototypal properties!
